### ISSUE TITLE
Unused pins 

### ISSUE THREAD

**Issue by kauly** [jeroennijhof/LoRaWAN#4]
In the board_config.py, how we define unused pins?  Getting always this AssertionError and I think it's because bad board configuration. I using the NiceRF LoRa1276 and a rasp zero w.

```
/home/pi/lora-testes/LoRaWAN/SX127x/board_config.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(BOARD.LED, GPIO.OUT)
Traceback (most recent call last):
  File "tx_ttn.py", line 40, in <module>
    lora = LoRaWANsend(False)
  File "tx_ttn.py", line 15, in __init__
    super(LoRaWANsend, self).__init__(verbose)
  File "/home/pi/lora-testes/LoRaWAN/SX127x/LoRa.py", line 100, in __init__
    self.rx_chain_calibration(calibration_freq)
  File "/home/pi/lora-testes/LoRaWAN/SX127x/LoRa.py", line 856, in rx_chain_calibration
    self.set_freq(freq_bkup)
  File "/home/pi/lora-testes/LoRaWAN/SX127x/LoRa.py", line 282, in set_freq
    assert self.mode == MODE.SLEEP or self.mode == MODE.STDBY or self.mode == MODE.FSK_STDBY
AssertionError

```

**Comment by zmarwa** [comment]
any solution for this please?

**Comment by jeroennijhof** [comment]
The python lib SX127x uses 4 DIO hardcoded and there functions are:
DIO0 00: RxDone
DIO0 01: TxDone
DIO0 10: CadDone
DIO1 00: RxTimeout
DIO1 01: FhssChangeChannel
DIO1 10: CadDetected
DIO2 00: FhssChangeChannel
DIO2 01: FhssChangeChannel
DIO2 10: FhssChangeChannel
DIO3 00: CadDone
DIO3 01: ValidHeader
DIO3 10: PayloadCrcError

Maybe you can check which functions are missing since the NiceRF chip has only 3 DIO, my guess is DIO2 so you could hack out all DIO2 functions and make sure DIO0, DIO1 and DIO3 are connected.

**Comment by rpsreal** [comment]
I have the same error with Raspberry Pi B+ and all the pins are connected.

**Comment by MikeRouten** [comment]
I am getting the same AssertionError because self.mode = 0.  This is with a Dragino Hat on top of a Pi 3.

Has anyone been able to resolve this issue?

Thanks in advance!
